---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
resources:
- deployment-nginx.yaml
images:
  - name: nginx
    newName: nginx
    newTag: 1.18.0
commonAnnotations:
  kubernetes.io/change-cause: "Initial deployment with 1.18.0"